apiVersion: apps/v1
kind: Deployment
metadata:
  name: adssa
  labels:
    app: adssa
  namespace: namespace-workflow-1688157232911
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adssa
  template:
    metadata:
      labels:
        app: adssa
    spec:
      containers:
        - name: adssa
          image: acrworkflow1688157232911.azurecr.io/image-workflow-1688157232911:latest
          ports:
            - containerPort: 5000