apiVersion: v1
kind: Service
metadata:
  name: dsd
  namespace: namespace-workflow-1686857254172
spec:
  type: LoadBalancer
  selector:
    app: dsd
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000