apiVersion: v1
kind: Service
metadata:
  name: abcde
  namespace: namespace-workflow-1686853170094
spec:
  type: LoadBalancer
  selector:
    app: abcde
  ports:
    - protocol: TCP
      port: 45003
      targetPort: 45003